{{- if eq .Values.jobWorkaround "enabled" }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: argo-ack-eks-{{ .Values.app }}
  name: argo-ack-eks-{{ .Values.app }}
  annotations:
    helm.sh/hook-weight: "50"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: argo-ack-eks-{{ .Values.app }}
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
        - name: argo-ack-eks
          image: {{ .Values.image }} # We need the aws-cli
          env:
          - name: EXPECTED_ASSUMED_ROLE_ARN
            value: {{ regexReplaceAll ":role/" .Values.roleArn ":assumed-role/" }}
          command:
            - sh
            - "-c"
            - "env | grep AWS_CONTAINER ; if [ $? -ne 0 ]; then echo 'No env set'; exit 1; else echo 'Found'; env; fi"
            - aws sts get-caller-identity --output text --query "Arn" | grep -qi "$EXPECTED_ASSUMED_ROLE_ARN"; then echo "Found"; else exit 1; fi
  backoffLimit: 4
  activeDeadlineSeconds: 60
{{- end }}
